/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guidesign;

/**
 *
 * @author cloud
 */
public class DeviceInfo extends javax.swing.JFrame {

    /**
     * Creates new form DeviceInfo
     */
    public DeviceInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBasicInfo = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        tfieldName = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        tfieldLocation = new javax.swing.JTextField();
        label4 = new javax.swing.JLabel();
        scrollpane1 = new javax.swing.JScrollPane();
        tareaDescription = new javax.swing.JTextArea();
        cboxType = new javax.swing.JComboBox<>();
        label5 = new javax.swing.JLabel();
        labelLastAccess = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        tfieldLabel = new javax.swing.JTextField();
        panelSNMPInfo = new javax.swing.JPanel();
        label8 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        tfieldCommunity = new javax.swing.JTextField();
        cboxSNMPVersion = new javax.swing.JComboBox<>();
        label10 = new javax.swing.JLabel();
        tfieldPort = new javax.swing.JTextField();
        label11 = new javax.swing.JLabel();
        tfieldAddress = new javax.swing.JTextField();
        buttonSummary = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        buttonResources = new javax.swing.JButton();
        buttonAdvance = new javax.swing.JButton();
        labelHidePanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1160, 940));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBasicInfo.setBackground(java.awt.Color.white);
        panelBasicInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Basic Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14))); // NOI18N
        panelBasicInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        label1.setText("Name:");
        panelBasicInfo.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, 30));

        tfieldName.setBackground(java.awt.Color.white);
        tfieldName.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        panelBasicInfo.add(tfieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 350, 30));

        label2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        label2.setText("Type:");
        panelBasicInfo.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, 30));

        label3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        label3.setText("Location:");
        panelBasicInfo.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, 30));

        tfieldLocation.setBackground(java.awt.Color.white);
        tfieldLocation.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        panelBasicInfo.add(tfieldLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 350, 30));

        label4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        label4.setText("Description:");
        panelBasicInfo.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, 30));

        scrollpane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollpane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tareaDescription.setBackground(java.awt.Color.white);
        tareaDescription.setColumns(20);
        tareaDescription.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tareaDescription.setRows(5);
        scrollpane1.setViewportView(tareaDescription);

        panelBasicInfo.add(scrollpane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 350, 120));

        cboxType.setBackground(java.awt.Color.white);
        cboxType.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cboxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelBasicInfo.add(cboxType, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 180, -1));

        label5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        label5.setText("Last Access:");
        panelBasicInfo.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, 30));

        labelLastAccess.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        labelLastAccess.setText(". . .");
        panelBasicInfo.add(labelLastAccess, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 350, 30));

        label6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        label6.setText("Label:");
        panelBasicInfo.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, 30));

        tfieldLabel.setBackground(java.awt.Color.white);
        tfieldLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        panelBasicInfo.add(tfieldLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 350, 30));

        getContentPane().add(panelBasicInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 920, 500));

        panelSNMPInfo.setBackground(java.awt.Color.white);
        panelSNMPInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "SNMP Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14))); // NOI18N
        panelSNMPInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        label8.setText("SNMP Version:");
        panelSNMPInfo.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, 30));

        label9.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        label9.setText("Community:");
        panelSNMPInfo.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, 30));

        tfieldCommunity.setBackground(java.awt.Color.white);
        tfieldCommunity.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        panelSNMPInfo.add(tfieldCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 350, 30));

        cboxSNMPVersion.setBackground(java.awt.Color.white);
        cboxSNMPVersion.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cboxSNMPVersion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelSNMPInfo.add(cboxSNMPVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 180, -1));

        label10.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        label10.setText("Port:");
        panelSNMPInfo.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, -1, 30));

        tfieldPort.setBackground(java.awt.Color.white);
        tfieldPort.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tfieldPort.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfieldPort.setText("161");
        panelSNMPInfo.add(tfieldPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 70, 30));

        label11.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        label11.setText("IP Address:");
        panelSNMPInfo.add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, 30));

        tfieldAddress.setBackground(java.awt.Color.white);
        tfieldAddress.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        panelSNMPInfo.add(tfieldAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 350, 30));

        getContentPane().add(panelSNMPInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 920, 210));

        buttonSummary.setBackground(new java.awt.Color(207, 62, 69));
        buttonSummary.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonSummary.setForeground(java.awt.Color.white);
        buttonSummary.setText("Summary");
        buttonSummary.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonSummary.setOpaque(true);
        getContentPane().add(buttonSummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 830, 100, 40));

        buttonCancel.setBackground(new java.awt.Color(38, 56, 163));
        buttonCancel.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonCancel.setForeground(java.awt.Color.white);
        buttonCancel.setText("Cancel");
        buttonCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonCancel.setOpaque(true);
        getContentPane().add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 830, 90, 40));

        buttonSave.setBackground(new java.awt.Color(38, 56, 163));
        buttonSave.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonSave.setForeground(java.awt.Color.white);
        buttonSave.setText("Save");
        buttonSave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonSave.setOpaque(true);
        getContentPane().add(buttonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 830, 100, 40));

        buttonResources.setBackground(new java.awt.Color(207, 62, 69));
        buttonResources.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonResources.setForeground(java.awt.Color.white);
        buttonResources.setText("Resources");
        buttonResources.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonResources.setOpaque(true);
        getContentPane().add(buttonResources, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 830, 100, 40));

        buttonAdvance.setBackground(new java.awt.Color(207, 62, 69));
        buttonAdvance.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonAdvance.setForeground(java.awt.Color.white);
        buttonAdvance.setText("Advance");
        buttonAdvance.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonAdvance.setOpaque(true);
        getContentPane().add(buttonAdvance, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 830, 100, 40));

        labelHidePanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_double_right_40.png"))); // NOI18N
        getContentPane().add(labelHidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeviceInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeviceInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeviceInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeviceInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeviceInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdvance;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonResources;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonSummary;
    private javax.swing.JComboBox<String> cboxSNMPVersion;
    private javax.swing.JComboBox<String> cboxType;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JLabel labelHidePanel;
    private javax.swing.JLabel labelLastAccess;
    private javax.swing.JPanel panelBasicInfo;
    private javax.swing.JPanel panelSNMPInfo;
    private javax.swing.JScrollPane scrollpane1;
    private javax.swing.JTextArea tareaDescription;
    private javax.swing.JTextField tfieldAddress;
    private javax.swing.JTextField tfieldCommunity;
    private javax.swing.JTextField tfieldLabel;
    private javax.swing.JTextField tfieldLocation;
    private javax.swing.JTextField tfieldName;
    private javax.swing.JTextField tfieldPort;
    // End of variables declaration//GEN-END:variables
}
