/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guidesign;

/**
 *
 * @author cloud
 */
public class DialogTemplateAddition extends javax.swing.JDialog {

    /**
     * Creates new form DialogAddingTemplates
     */
    public DialogTemplateAddition(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollpaneTemplates = new javax.swing.JScrollPane();
        listTemplates = new javax.swing.JList<>();
        buttonAdd = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 700));
        setMinimumSize(new java.awt.Dimension(500, 700));
        setPreferredSize(new java.awt.Dimension(500, 700));
        getContentPane().setLayout(null);

        listTemplates.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        listTemplates.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listTemplates.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        listTemplates.setMaximumSize(new java.awt.Dimension(52, 400));
        listTemplates.setMinimumSize(new java.awt.Dimension(52, 400));
        listTemplates.setPreferredSize(new java.awt.Dimension(52, 400));
        scrollpaneTemplates.setViewportView(listTemplates);

        getContentPane().add(scrollpaneTemplates);
        scrollpaneTemplates.setBounds(49, 57, 392, 531);

        buttonAdd.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        buttonAdd.setText("Add");
        buttonAdd.setMaximumSize(new java.awt.Dimension(80, 30));
        buttonAdd.setMinimumSize(new java.awt.Dimension(80, 30));
        buttonAdd.setPreferredSize(new java.awt.Dimension(80, 30));
        getContentPane().add(buttonAdd);
        buttonAdd.setBounds(260, 620, 80, 30);

        buttonCancel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        buttonCancel.setText("Cancel");
        buttonCancel.setMaximumSize(new java.awt.Dimension(80, 30));
        buttonCancel.setMinimumSize(new java.awt.Dimension(80, 30));
        buttonCancel.setPreferredSize(new java.awt.Dimension(80, 30));
        getContentPane().add(buttonCancel);
        buttonCancel.setBounds(360, 620, 80, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogTemplateAddition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogTemplateAddition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogTemplateAddition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogTemplateAddition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogTemplateAddition dialog = new DialogTemplateAddition(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JList<String> listTemplates;
    private javax.swing.JScrollPane scrollpaneTemplates;
    // End of variables declaration//GEN-END:variables
}
