/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guidesign;

/**
 *
 * @author cloud
 */
public class DialogChoosingTemplates extends javax.swing.JDialog {

    /**
     * Creates new form DialogChoosingTemplates
     */
    public DialogChoosingTemplates(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollpane1 = new javax.swing.JScrollPane();
        listTemplates = new javax.swing.JList<>();
        buttonCancel = new javax.swing.JButton();
        buttonTabular = new javax.swing.JButton();
        buttonContinue = new javax.swing.JButton();
        buttonSingular = new javax.swing.JButton();
        tfieldSearch = new javax.swing.JTextField();
        labelIcon1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setMaximumSize(new java.awt.Dimension(444, 615));
        setMinimumSize(new java.awt.Dimension(444, 615));
        setModal(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listTemplates.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        listTemplates.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollpane1.setViewportView(listTemplates);

        getContentPane().add(scrollpane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 320, 380));

        buttonCancel.setBackground(new java.awt.Color(66, 108, 245));
        buttonCancel.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonCancel.setForeground(java.awt.Color.white);
        buttonCancel.setText("Cancel");
        buttonCancel.setBorderPainted(false);
        getContentPane().add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 90, -1));

        buttonTabular.setBackground(new java.awt.Color(152, 181, 245));
        buttonTabular.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonTabular.setForeground(java.awt.Color.white);
        buttonTabular.setText("Tabular");
        buttonTabular.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        getContentPane().add(buttonTabular, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 80, 30));

        buttonContinue.setBackground(new java.awt.Color(66, 108, 245));
        buttonContinue.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonContinue.setForeground(java.awt.Color.white);
        buttonContinue.setText("Continue");
        buttonContinue.setBorderPainted(false);
        getContentPane().add(buttonContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, -1, -1));

        buttonSingular.setBackground(new java.awt.Color(66, 108, 245));
        buttonSingular.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonSingular.setForeground(java.awt.Color.white);
        buttonSingular.setText("Singular");
        buttonSingular.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        getContentPane().add(buttonSingular, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 80, 30));

        tfieldSearch.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        getContentPane().add(tfieldSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 280, 30));

        labelIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_search2_30.png"))); // NOI18N
        getContentPane().add(labelIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 40, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogChoosingTemplates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogChoosingTemplates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogChoosingTemplates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogChoosingTemplates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogChoosingTemplates dialog = new DialogChoosingTemplates(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonContinue;
    private javax.swing.JButton buttonSingular;
    private javax.swing.JButton buttonTabular;
    private javax.swing.JLabel labelIcon1;
    private javax.swing.JList<String> listTemplates;
    private javax.swing.JScrollPane scrollpane1;
    private javax.swing.JTextField tfieldSearch;
    // End of variables declaration//GEN-END:variables
}
