/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guidesign;

/**
 *
 * @author cloud
 */
public class DialogChoosingTemplates extends javax.swing.JDialog {

    /**
     * Creates new form DialogChoosingTemplates
     */
    public DialogChoosingTemplates(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelChoosingTabular = new javax.swing.JLabel();
        labelChoosingSingular = new javax.swing.JLabel();
        scrollpane1 = new javax.swing.JScrollPane();
        listTemplates = new javax.swing.JList<>();
        buttonCancel = new javax.swing.JButton();
        buttonContinue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setMaximumSize(new java.awt.Dimension(444, 615));
        setMinimumSize(new java.awt.Dimension(444, 615));
        setModal(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelChoosingTabular.setBackground(new java.awt.Color(66, 245, 156));
        labelChoosingTabular.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelChoosingTabular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelChoosingTabular.setText("Tabular");
        labelChoosingTabular.setOpaque(true);
        getContentPane().add(labelChoosingTabular, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 70, 50));

        labelChoosingSingular.setBackground(new java.awt.Color(66, 135, 245));
        labelChoosingSingular.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelChoosingSingular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelChoosingSingular.setText("Singular");
        labelChoosingSingular.setOpaque(true);
        getContentPane().add(labelChoosingSingular, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 70, 50));

        listTemplates.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        listTemplates.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollpane1.setViewportView(listTemplates);

        getContentPane().add(scrollpane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 320, 410));

        buttonCancel.setBackground(new java.awt.Color(66, 108, 245));
        buttonCancel.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonCancel.setForeground(java.awt.Color.white);
        buttonCancel.setText("Cancel");
        buttonCancel.setBorderPainted(false);
        getContentPane().add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 90, -1));

        buttonContinue.setBackground(new java.awt.Color(66, 108, 245));
        buttonContinue.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonContinue.setForeground(java.awt.Color.white);
        buttonContinue.setText("Continue");
        buttonContinue.setBorderPainted(false);
        getContentPane().add(buttonContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogChoosingTemplates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogChoosingTemplates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogChoosingTemplates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogChoosingTemplates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogChoosingTemplates dialog = new DialogChoosingTemplates(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonContinue;
    private javax.swing.JLabel labelChoosingSingular;
    private javax.swing.JLabel labelChoosingTabular;
    private javax.swing.JList<String> listTemplates;
    private javax.swing.JScrollPane scrollpane1;
    // End of variables declaration//GEN-END:variables
}
