/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guidesign;

import java.awt.Color;

/**
 *
 * @author cloud
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegister = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        panelRegister.setBackground(new java.awt.Color(254, 254, 254));
        panelRegister.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 254, 254), 3, true));
        panelRegister.setMaximumSize(new java.awt.Dimension(510, 540));
        panelRegister.setMinimumSize(new java.awt.Dimension(510, 540));
        panelRegister.setPreferredSize(new java.awt.Dimension(510, 540));
        panelRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(20, 60, 227));
        jLabel6.setText("or");
        jLabel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelRegister.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, -1));

        jTextField2.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(22, 96, 241)));
        jTextField2.setCaretColor(new java.awt.Color(1, 1, 1));
        jTextField2.setOpaque(false);
        panelRegister.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 350, 40));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(20, 60, 227));
        jLabel7.setText("password");
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelRegister.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jButton3.setBackground(new java.awt.Color(126, 80, 241));
        jButton3.setForeground(new java.awt.Color(254, 254, 254));
        jButton3.setText("Cancel");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        panelRegister.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 230, 40));

        jTextField4.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(22, 96, 241)));
        jTextField4.setCaretColor(new java.awt.Color(1, 1, 1));
        jTextField4.setOpaque(false);
        panelRegister.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 350, 40));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(20, 60, 227));
        jLabel8.setText("username");
        jLabel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelRegister.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jButton4.setBackground(new java.awt.Color(126, 80, 241));
        jButton4.setForeground(new java.awt.Color(254, 254, 254));
        jButton4.setText("Create");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelRegister.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 230, 40));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(20, 60, 227));
        jLabel10.setText("name");
        jLabel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelRegister.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jTextField5.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(22, 96, 241)));
        jTextField5.setCaretColor(new java.awt.Color(1, 1, 1));
        jTextField5.setOpaque(false);
        panelRegister.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 350, 40));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(20, 60, 227));
        jLabel11.setText("occupation");
        jLabel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelRegister.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jTextField6.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextField6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(22, 96, 241)));
        jTextField6.setCaretColor(new java.awt.Color(1, 1, 1));
        jTextField6.setOpaque(false);
        panelRegister.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 350, 40));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setMinimumSize(new java.awt.Dimension(1600, 1000));
        jPanel1.setPreferredSize(new java.awt.Dimension(1600, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new Color(0, 0, 0, 100));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setMaximumSize(new java.awt.Dimension(1600, 1000));
        jPanel2.setMinimumSize(new java.awt.Dimension(1600, 1000));
        jPanel2.setPreferredSize(new java.awt.Dimension(1600, 1000));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogin.setBackground(new java.awt.Color(254, 254, 254));
        panelLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 254, 254), 3, true));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(20, 60, 227));
        jLabel2.setText("or");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, -1));

        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(22, 96, 241)));
        jTextField1.setCaretColor(new java.awt.Color(1, 1, 1));
        jTextField1.setOpaque(false);
        panelLogin.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 350, 40));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(20, 60, 227));
        jLabel3.setText("password");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jButton1.setBackground(new java.awt.Color(126, 80, 241));
        jButton1.setForeground(new java.awt.Color(254, 254, 254));
        jButton1.setText("Register");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        panelLogin.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 230, 40));

        jTextField3.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(22, 96, 241)));
        jTextField3.setCaretColor(new java.awt.Color(1, 1, 1));
        jTextField3.setOpaque(false);
        panelLogin.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 350, 40));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(20, 60, 227));
        jLabel4.setText("username");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jButton2.setBackground(new java.awt.Color(126, 80, 241));
        jButton2.setForeground(new java.awt.Color(254, 254, 254));
        jButton2.setText("Login");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelLogin.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 230, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account_icon.png"))); // NOI18N
        panelLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jPanel2.add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 510, 540));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(1, 1, 1));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/network_icon.jpg"))); // NOI18N
        jLabel1.setBorder(null);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.out.println("Switching the login panel");
        jPanel2.remove(panelLogin);
        jPanel2.add(panelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 510, 540));
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelRegister;
    // End of variables declaration//GEN-END:variables
}
