/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guidesign;

/**
 *
 * @author cloud
 */
public class P extends javax.swing.JFrame {

    /**
     * Creates new form P
     */
    public P() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAccount = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        labelFullname = new javax.swing.JLabel();
        labelAge = new javax.swing.JLabel();
        labelPosition = new javax.swing.JLabel();
        labelContactNumber = new javax.swing.JLabel();
        labelAccountValue = new javax.swing.JLabel();
        labelConfirm = new javax.swing.JLabel();
        tfieldFullname = new javax.swing.JTextField();
        tfieldAge = new javax.swing.JTextField();
        tfieldPosition = new javax.swing.JTextField();
        tfieldContactNumber = new javax.swing.JTextField();
        tfieldPassword = new javax.swing.JPasswordField();
        tfieldConfirm = new javax.swing.JPasswordField();
        buttonCancelPassword = new javax.swing.JButton();
        buttonSaveInfo = new javax.swing.JButton();
        buttonCancelInfo = new javax.swing.JButton();
        buttonChangePassword = new javax.swing.JButton();
        panelImage = new javax.swing.JPanel();
        labelImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1500, 900));
        setMinimumSize(new java.awt.Dimension(1500, 900));
        setPreferredSize(new java.awt.Dimension(1500, 900));
        getContentPane().setLayout(null);

        labelAccount.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        labelAccount.setText("Account:");
        labelAccount.setMaximumSize(new java.awt.Dimension(100, 30));
        labelAccount.setMinimumSize(new java.awt.Dimension(100, 30));
        labelAccount.setPreferredSize(new java.awt.Dimension(100, 30));
        getContentPane().add(labelAccount);
        labelAccount.setBounds(320, 570, 100, 30);

        labelPassword.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        labelPassword.setText("Password:");
        labelPassword.setMaximumSize(new java.awt.Dimension(100, 30));
        labelPassword.setMinimumSize(new java.awt.Dimension(100, 30));
        labelPassword.setPreferredSize(new java.awt.Dimension(100, 30));
        getContentPane().add(labelPassword);
        labelPassword.setBounds(320, 610, 100, 30);

        labelFullname.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        labelFullname.setText("Full name:");
        labelFullname.setMaximumSize(new java.awt.Dimension(150, 30));
        labelFullname.setMinimumSize(new java.awt.Dimension(150, 30));
        labelFullname.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(labelFullname);
        labelFullname.setBounds(880, 190, 150, 30);

        labelAge.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        labelAge.setText("Age:");
        labelAge.setMaximumSize(new java.awt.Dimension(150, 30));
        labelAge.setMinimumSize(new java.awt.Dimension(150, 30));
        labelAge.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(labelAge);
        labelAge.setBounds(880, 230, 150, 30);

        labelPosition.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        labelPosition.setText("Position:");
        labelPosition.setMaximumSize(new java.awt.Dimension(150, 30));
        labelPosition.setMinimumSize(new java.awt.Dimension(150, 30));
        labelPosition.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(labelPosition);
        labelPosition.setBounds(880, 270, 150, 30);

        labelContactNumber.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        labelContactNumber.setText("Contact number:");
        labelContactNumber.setMaximumSize(new java.awt.Dimension(150, 30));
        labelContactNumber.setMinimumSize(new java.awt.Dimension(150, 30));
        labelContactNumber.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(labelContactNumber);
        labelContactNumber.setBounds(880, 310, 150, 30);

        labelAccountValue.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        labelAccountValue.setText(". . .");
        labelAccountValue.setMaximumSize(new java.awt.Dimension(200, 30));
        labelAccountValue.setMinimumSize(new java.awt.Dimension(200, 30));
        labelAccountValue.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(labelAccountValue);
        labelAccountValue.setBounds(440, 570, 200, 30);

        labelConfirm.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        labelConfirm.setText("Confirm:");
        labelConfirm.setMaximumSize(new java.awt.Dimension(100, 30));
        labelConfirm.setMinimumSize(new java.awt.Dimension(100, 30));
        labelConfirm.setPreferredSize(new java.awt.Dimension(100, 30));
        getContentPane().add(labelConfirm);
        labelConfirm.setBounds(320, 660, 100, 30);

        tfieldFullname.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tfieldFullname.setMaximumSize(new java.awt.Dimension(200, 30));
        tfieldFullname.setMinimumSize(new java.awt.Dimension(200, 30));
        tfieldFullname.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(tfieldFullname);
        tfieldFullname.setBounds(1030, 190, 200, 30);

        tfieldAge.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tfieldAge.setMaximumSize(new java.awt.Dimension(200, 30));
        tfieldAge.setMinimumSize(new java.awt.Dimension(200, 30));
        tfieldAge.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(tfieldAge);
        tfieldAge.setBounds(1030, 230, 200, 30);

        tfieldPosition.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tfieldPosition.setMaximumSize(new java.awt.Dimension(200, 30));
        tfieldPosition.setMinimumSize(new java.awt.Dimension(200, 30));
        tfieldPosition.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(tfieldPosition);
        tfieldPosition.setBounds(1030, 270, 200, 30);

        tfieldContactNumber.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tfieldContactNumber.setMaximumSize(new java.awt.Dimension(200, 30));
        tfieldContactNumber.setMinimumSize(new java.awt.Dimension(200, 30));
        tfieldContactNumber.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(tfieldContactNumber);
        tfieldContactNumber.setBounds(1030, 310, 200, 30);

        tfieldPassword.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tfieldPassword.setMaximumSize(new java.awt.Dimension(200, 30));
        tfieldPassword.setMinimumSize(new java.awt.Dimension(200, 30));
        tfieldPassword.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(tfieldPassword);
        tfieldPassword.setBounds(440, 610, 200, 30);

        tfieldConfirm.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tfieldConfirm.setMaximumSize(new java.awt.Dimension(200, 30));
        tfieldConfirm.setMinimumSize(new java.awt.Dimension(200, 30));
        tfieldConfirm.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(tfieldConfirm);
        tfieldConfirm.setBounds(440, 660, 200, 30);

        buttonCancelPassword.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        buttonCancelPassword.setText("Cancel");
        buttonCancelPassword.setMaximumSize(new java.awt.Dimension(80, 30));
        buttonCancelPassword.setMinimumSize(new java.awt.Dimension(80, 30));
        buttonCancelPassword.setPreferredSize(new java.awt.Dimension(80, 30));
        getContentPane().add(buttonCancelPassword);
        buttonCancelPassword.setBounds(660, 660, 80, 30);

        buttonSaveInfo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        buttonSaveInfo.setText("Save");
        buttonSaveInfo.setMaximumSize(new java.awt.Dimension(80, 30));
        buttonSaveInfo.setMinimumSize(new java.awt.Dimension(80, 30));
        buttonSaveInfo.setPreferredSize(new java.awt.Dimension(80, 30));
        buttonSaveInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveInfoActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSaveInfo);
        buttonSaveInfo.setBounds(1050, 370, 80, 30);

        buttonCancelInfo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        buttonCancelInfo.setText("Cancel");
        buttonCancelInfo.setMaximumSize(new java.awt.Dimension(80, 30));
        buttonCancelInfo.setMinimumSize(new java.awt.Dimension(80, 30));
        buttonCancelInfo.setPreferredSize(new java.awt.Dimension(80, 30));
        getContentPane().add(buttonCancelInfo);
        buttonCancelInfo.setBounds(1140, 370, 80, 30);

        buttonChangePassword.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        buttonChangePassword.setText("Change");
        buttonChangePassword.setMaximumSize(new java.awt.Dimension(80, 30));
        buttonChangePassword.setMinimumSize(new java.awt.Dimension(80, 30));
        buttonChangePassword.setPreferredSize(new java.awt.Dimension(80, 30));
        getContentPane().add(buttonChangePassword);
        buttonChangePassword.setBounds(660, 610, 80, 30);

        panelImage.setLayout(null);

        labelImage.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        labelImage.setText("Image");
        panelImage.add(labelImage);
        labelImage.setBounds(110, 120, 80, 40);

        getContentPane().add(panelImage);
        panelImage.setBounds(400, 130, 290, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSaveInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSaveInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelInfo;
    private javax.swing.JButton buttonCancelPassword;
    private javax.swing.JButton buttonChangePassword;
    private javax.swing.JButton buttonSaveInfo;
    private javax.swing.JLabel labelAccount;
    private javax.swing.JLabel labelAccountValue;
    private javax.swing.JLabel labelAge;
    private javax.swing.JLabel labelConfirm;
    private javax.swing.JLabel labelContactNumber;
    private javax.swing.JLabel labelFullname;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelPosition;
    private javax.swing.JPanel panelImage;
    private javax.swing.JTextField tfieldAge;
    private javax.swing.JPasswordField tfieldConfirm;
    private javax.swing.JTextField tfieldContactNumber;
    private javax.swing.JTextField tfieldFullname;
    private javax.swing.JPasswordField tfieldPassword;
    private javax.swing.JTextField tfieldPosition;
    // End of variables declaration//GEN-END:variables
}
