/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guidesign;

import java.awt.Color;

/**
 *
 * @author cloud
 */
public class PanelItemInfo extends javax.swing.JFrame {

    /**
     * Creates new form PanelItemInfo
     */
    public PanelItemInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOverlay = new javax.swing.JPanel();
        panelItemInfo = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        tfieldDisplayName = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        labelValueType = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        labelAccessType = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        scrollpane1 = new javax.swing.JScrollPane();
        tareaDescription = new javax.swing.JTextArea();
        buttonCancel = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        labelIconBack = new javax.swing.JLabel();
        labelMIBName = new javax.swing.JLabel();
        labelOID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelOverlay.setBackground(new Color(0, 0, 0, 150));
        panelOverlay.setPreferredSize(new java.awt.Dimension(1160, 940));
        panelOverlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelItemInfo.setBackground(java.awt.Color.white);
        panelItemInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label1.setText("Display Name:");
        panelItemInfo.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, 30));

        tfieldDisplayName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tfieldDisplayName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelItemInfo.add(tfieldDisplayName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 360, 30));

        label2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label2.setText("MIB Name:");
        panelItemInfo.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, 30));

        label3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label3.setText("Object ID:");
        panelItemInfo.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, 30));

        labelValueType.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelValueType.setText(". . .");
        panelItemInfo.add(labelValueType, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 320, 30));

        label4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label4.setText("Value Type:");
        panelItemInfo.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, 30));

        labelAccessType.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelAccessType.setText(". . .");
        panelItemInfo.add(labelAccessType, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 320, 30));

        label5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label5.setText("Description:");
        panelItemInfo.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, 30));

        label6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label6.setText("Access Type:");
        panelItemInfo.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, 30));

        tareaDescription.setColumns(20);
        tareaDescription.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        tareaDescription.setLineWrap(true);
        tareaDescription.setRows(5);
        tareaDescription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scrollpane1.setViewportView(tareaDescription);

        panelItemInfo.add(scrollpane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 360, 160));

        buttonCancel.setBackground(new java.awt.Color(73, 125, 222));
        buttonCancel.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonCancel.setForeground(java.awt.Color.white);
        buttonCancel.setText("Cancel");
        panelItemInfo.add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 590, 90, 40));

        buttonSave.setBackground(new java.awt.Color(73, 125, 222));
        buttonSave.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonSave.setForeground(java.awt.Color.white);
        buttonSave.setText("Save");
        panelItemInfo.add(buttonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, 90, 40));

        labelIconBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIconBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_arrow_back80.png"))); // NOI18N
        panelItemInfo.add(labelIconBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        labelMIBName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelMIBName.setText(". . .");
        panelItemInfo.add(labelMIBName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 320, 30));

        labelOID.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelOID.setText(". . .");
        panelItemInfo.add(labelOID, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 320, 30));

        panelOverlay.add(panelItemInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 710, 680));

        getContentPane().add(panelOverlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelItemInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelItemInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelItemInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelItemInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelItemInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonSave;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel labelAccessType;
    private javax.swing.JLabel labelIconBack;
    private javax.swing.JLabel labelMIBName;
    private javax.swing.JLabel labelOID;
    private javax.swing.JLabel labelValueType;
    private javax.swing.JPanel panelItemInfo;
    private javax.swing.JPanel panelOverlay;
    private javax.swing.JScrollPane scrollpane1;
    private javax.swing.JTextArea tareaDescription;
    private javax.swing.JTextField tfieldDisplayName;
    // End of variables declaration//GEN-END:variables
}
