/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guidesign;

import java.awt.Color;

/**
 *
 * @author cloud
 */
public class PanelChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form PanelChangePassword
     */
    public PanelChangePassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOverlay = new javax.swing.JPanel();
        panelChangePassword = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        labelErrorInform = new javax.swing.JLabel();
        buttonCancel = new javax.swing.JButton();
        buttonChange = new javax.swing.JButton();
        scrollpane1 = new javax.swing.JScrollPane();
        tarea1 = new javax.swing.JTextArea();
        pfieldConfirmPassword = new javax.swing.JPasswordField();
        pfieldOldPassword = new javax.swing.JPasswordField();
        pfieldNewPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 940));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelOverlay.setBackground(new Color(0, 0, 0, 150));
        panelOverlay.setPreferredSize(new java.awt.Dimension(1600, 940));

        panelChangePassword.setBackground(java.awt.Color.white);
        panelChangePassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setBackground(new java.awt.Color(56, 48, 130));
        label1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        label1.setForeground(new java.awt.Color(56, 48, 130));
        label1.setText("Old Password");
        panelChangePassword.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        label2.setBackground(new java.awt.Color(56, 48, 130));
        label2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        label2.setForeground(new java.awt.Color(56, 48, 130));
        label2.setText("New Password");
        panelChangePassword.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        label3.setBackground(new java.awt.Color(56, 48, 130));
        label3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        label3.setForeground(new java.awt.Color(56, 48, 130));
        label3.setText("Confirm Password");
        panelChangePassword.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        labelErrorInform.setForeground(java.awt.Color.red);
        labelErrorInform.setText(". . .");
        panelChangePassword.add(labelErrorInform, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 360, -1));

        buttonCancel.setBackground(new java.awt.Color(48, 59, 130));
        buttonCancel.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonCancel.setForeground(java.awt.Color.white);
        buttonCancel.setText("Cancel");
        buttonCancel.setBorderPainted(false);
        panelChangePassword.add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 100, 40));

        buttonChange.setBackground(new java.awt.Color(48, 59, 130));
        buttonChange.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonChange.setForeground(java.awt.Color.white);
        buttonChange.setText("Change");
        buttonChange.setBorderPainted(false);
        panelChangePassword.add(buttonChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 100, 40));

        scrollpane1.setBorder(null);
        scrollpane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollpane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollpane1.setFocusable(false);
        scrollpane1.setOpaque(false);

        tarea1.setEditable(false);
        tarea1.setColumns(20);
        tarea1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tarea1.setLineWrap(true);
        tarea1.setRows(5);
        tarea1.setText("   Changing password will log you out. Youshould re-login to check your newly updated password.");
        tarea1.setWrapStyleWord(true);
        tarea1.setBorder(null);
        scrollpane1.setViewportView(tarea1);

        panelChangePassword.add(scrollpane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 350, 70));

        pfieldConfirmPassword.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        pfieldConfirmPassword.setText("jPasswordField1");
        pfieldConfirmPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pfieldConfirmPassword.setOpaque(false);
        pfieldConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfieldConfirmPasswordActionPerformed(evt);
            }
        });
        panelChangePassword.add(pfieldConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 350, 40));

        pfieldOldPassword.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        pfieldOldPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pfieldOldPassword.setOpaque(false);
        panelChangePassword.add(pfieldOldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 350, 40));

        pfieldNewPassword.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        pfieldNewPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pfieldNewPassword.setOpaque(false);
        panelChangePassword.add(pfieldNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 350, 40));

        javax.swing.GroupLayout panelOverlayLayout = new javax.swing.GroupLayout(panelOverlay);
        panelOverlay.setLayout(panelOverlayLayout);
        panelOverlayLayout.setHorizontalGroup(
            panelOverlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOverlayLayout.createSequentialGroup()
                .addContainerGap(553, Short.MAX_VALUE)
                .addComponent(panelChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(533, 533, 533))
        );
        panelOverlayLayout.setVerticalGroup(
            panelOverlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOverlayLayout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(panelChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );

        getContentPane().add(panelOverlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pfieldConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfieldConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfieldConfirmPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonChange;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel labelErrorInform;
    private javax.swing.JPanel panelChangePassword;
    private javax.swing.JPanel panelOverlay;
    private javax.swing.JPasswordField pfieldConfirmPassword;
    private javax.swing.JPasswordField pfieldNewPassword;
    private javax.swing.JPasswordField pfieldOldPassword;
    private javax.swing.JScrollPane scrollpane1;
    private javax.swing.JTextArea tarea1;
    // End of variables declaration//GEN-END:variables
}
