/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guidesign;

/**
 *
 * @author cloud
 */
public class PanelAccountInfo extends javax.swing.JFrame {

    /**
     * Creates new form PanelAccountInfo
     */
    public PanelAccountInfo() {
        initComponents();
//        this.getContentPane().remove(jLabel1);
//        this.jLabel1.setVisible(false);
//        this.jLabel1.setEnabled(false);
//        this.revalidate();
//        this.repaint();
//        this.jLabel1.setEnabled(true);
//        this.jLabel1.setVisible(true);        
//
//        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 230, 280));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAvatar = new javax.swing.JLabel();
        panelOverlay = new javax.swing.JPanel();
        panelAccountInformation = new javax.swing.JPanel();
        labelAccount = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        separator1 = new javax.swing.JSeparator();
        label2 = new javax.swing.JLabel();
        labelDisableAutoLogin = new javax.swing.JLabel();
        labelChangePassword = new javax.swing.JLabel();
        panelPersonalInformation = new javax.swing.JPanel();
        label3 = new javax.swing.JLabel();
        tfieldName = new javax.swing.JTextField();
        tfieldAge = new javax.swing.JTextField();
        label4 = new javax.swing.JLabel();
        tfieldPosition = new javax.swing.JTextField();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        tfieldPhone = new javax.swing.JTextField();
        tfieldEmail = new javax.swing.JTextField();
        label7 = new javax.swing.JLabel();
        buttonCancel = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 940));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelAvatar.setBackground(java.awt.Color.white);
        labelAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAvatar.setText("Avatar (40  x 20)");
        labelAvatar.setOpaque(true);
        labelAvatar.setPreferredSize(new java.awt.Dimension(40, 20));
        getContentPane().add(labelAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 230, 280));

        panelOverlay.setBackground(new java.awt.Color(73, 125, 222));

        javax.swing.GroupLayout panelOverlayLayout = new javax.swing.GroupLayout(panelOverlay);
        panelOverlay.setLayout(panelOverlayLayout);
        panelOverlayLayout.setHorizontalGroup(
            panelOverlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1600, Short.MAX_VALUE)
        );
        panelOverlayLayout.setVerticalGroup(
            panelOverlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        getContentPane().add(panelOverlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, -1));

        panelAccountInformation.setBackground(java.awt.Color.white);
        panelAccountInformation.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Account Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14))); // NOI18N
        panelAccountInformation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelAccount.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        labelAccount.setText(". . .");
        panelAccountInformation.add(labelAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 220, 40));

        label1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(73, 125, 222));
        label1.setText("Account");
        panelAccountInformation.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 80, 40));
        panelAccountInformation.add(separator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 470, 10));

        label2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(73, 125, 222));
        label2.setText("Password");
        panelAccountInformation.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 130, 40));

        labelDisableAutoLogin.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelDisableAutoLogin.setForeground(new java.awt.Color(222, 73, 88));
        labelDisableAutoLogin.setText("Disable Auto Login");
        panelAccountInformation.add(labelDisableAutoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 220, 40));

        labelChangePassword.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        labelChangePassword.setForeground(java.awt.Color.blue);
        labelChangePassword.setText("Change password");
        panelAccountInformation.add(labelChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 220, 40));

        getContentPane().add(panelAccountInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 470, 260));

        panelPersonalInformation.setBackground(java.awt.Color.white);
        panelPersonalInformation.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Personal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14))); // NOI18N
        panelPersonalInformation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label3.setBackground(new java.awt.Color(73, 125, 222));
        label3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        label3.setForeground(new java.awt.Color(73, 125, 222));
        label3.setText("Name:");
        panelPersonalInformation.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, 20));

        tfieldName.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tfieldName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tfieldName.setOpaque(false);
        panelPersonalInformation.add(tfieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 342, 30));

        tfieldAge.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tfieldAge.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tfieldAge.setOpaque(false);
        panelPersonalInformation.add(tfieldAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 342, 30));

        label4.setBackground(new java.awt.Color(73, 125, 222));
        label4.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        label4.setForeground(new java.awt.Color(73, 125, 222));
        label4.setText("Age:");
        panelPersonalInformation.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, 20));

        tfieldPosition.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tfieldPosition.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tfieldPosition.setOpaque(false);
        panelPersonalInformation.add(tfieldPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 342, 30));

        label5.setBackground(new java.awt.Color(73, 125, 222));
        label5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        label5.setForeground(new java.awt.Color(73, 125, 222));
        label5.setText("Position:");
        panelPersonalInformation.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, 20));

        label6.setBackground(new java.awt.Color(73, 125, 222));
        label6.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        label6.setForeground(new java.awt.Color(73, 125, 222));
        label6.setText("Phone:");
        panelPersonalInformation.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, 20));

        tfieldPhone.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tfieldPhone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tfieldPhone.setOpaque(false);
        panelPersonalInformation.add(tfieldPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 342, 30));

        tfieldEmail.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tfieldEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tfieldEmail.setOpaque(false);
        panelPersonalInformation.add(tfieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 342, 30));

        label7.setBackground(new java.awt.Color(73, 125, 222));
        label7.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        label7.setForeground(new java.awt.Color(73, 125, 222));
        label7.setText("Email:");
        panelPersonalInformation.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, 20));

        getContentPane().add(panelPersonalInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 760, 460));

        buttonCancel.setBackground(new java.awt.Color(73, 125, 222));
        buttonCancel.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonCancel.setForeground(java.awt.Color.white);
        buttonCancel.setText("Cancel");
        buttonCancel.setBorder(null);
        buttonCancel.setBorderPainted(false);
        getContentPane().add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 830, 90, 40));

        buttonSave.setBackground(new java.awt.Color(73, 125, 222));
        buttonSave.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonSave.setForeground(java.awt.Color.white);
        buttonSave.setText("Save");
        buttonSave.setBorder(null);
        buttonSave.setBorderPainted(false);
        getContentPane().add(buttonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 830, 90, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelAccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelAccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelAccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelAccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelAccountInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonSave;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel labelAccount;
    private javax.swing.JLabel labelAvatar;
    private javax.swing.JLabel labelChangePassword;
    private javax.swing.JLabel labelDisableAutoLogin;
    private javax.swing.JPanel panelAccountInformation;
    private javax.swing.JPanel panelOverlay;
    private javax.swing.JPanel panelPersonalInformation;
    private javax.swing.JSeparator separator1;
    private javax.swing.JTextField tfieldAge;
    private javax.swing.JTextField tfieldEmail;
    private javax.swing.JTextField tfieldName;
    private javax.swing.JTextField tfieldPhone;
    private javax.swing.JTextField tfieldPosition;
    // End of variables declaration//GEN-END:variables
}
