/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guidesign;

/**
 *
 * @author cloud
 */
public class PanelDeviceSummary extends javax.swing.JFrame {

    /**
     * Creates new form PanelDeviceSummary
     */
    public PanelDeviceSummary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        button7days = new javax.swing.JRadioButton();
        buttonToday = new javax.swing.JRadioButton();
        buttonYesterday = new javax.swing.JRadioButton();
        button3days = new javax.swing.JRadioButton();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        cboxInterfaces = new javax.swing.JComboBox<>();
        label6 = new javax.swing.JLabel();
        cboxMemory = new javax.swing.JComboBox<>();
        label7 = new javax.swing.JLabel();
        cboxCPU = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1160, 940));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        label1.setText("CPU Load:");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 90, 30));

        button7days.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        button7days.setText("Last 7 days");
        getContentPane().add(button7days, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 40, -1, 30));

        buttonToday.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        buttonToday.setText("Today");
        getContentPane().add(buttonToday, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, 30));

        buttonYesterday.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        buttonYesterday.setText("Yesterday");
        getContentPane().add(buttonYesterday, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, -1, 30));

        button3days.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        button3days.setText("Last 3 days");
        getContentPane().add(button3days, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, -1, 30));

        label2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        label2.setText("Period:");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, 30));

        label3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        label3.setText("RAM Usage:");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, 30));

        label4.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        label4.setText("Interface");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 610, -1, 30));

        label5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        label5.setText("Bandwidth Utilization:");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, -1, 30));

        cboxInterfaces.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        cboxInterfaces.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cboxInterfaces, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 610, 290, 30));

        label6.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        label6.setText("Memory");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, -1, 30));

        cboxMemory.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        cboxMemory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cboxMemory, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, 290, 30));

        label7.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        label7.setText("CPU");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 80, 50, 30));

        cboxCPU.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        cboxCPU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cboxCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, 290, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelDeviceSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelDeviceSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelDeviceSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelDeviceSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelDeviceSummary().setVisible(true);
            }
        });
    }

    private void memorizePanelPosition() {
//        getContentPane().add(panelCPULoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 990, 190));
//        getContentPane().add(panelRamUsage, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 990, 190));
//        getContentPane().add(panelBandwidthUtilization, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 650, 990, 190));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton button3days;
    private javax.swing.JRadioButton button7days;
    private javax.swing.JRadioButton buttonToday;
    private javax.swing.JRadioButton buttonYesterday;
    private javax.swing.JComboBox<String> cboxCPU;
    private javax.swing.JComboBox<String> cboxInterfaces;
    private javax.swing.JComboBox<String> cboxMemory;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    // End of variables declaration//GEN-END:variables
}
