/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guidesign;

/**
 *
 * @author cloud
 */
public class PanelMonitoringDevices extends javax.swing.JFrame {

    /**
     * Creates new form PanelDisplayTemplates
     */
    public PanelMonitoringDevices() {
        initComponents();
        this.tableItems.setShowGrid(false);
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTemplateInfo = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        tfieldTemplateName = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        tfieldDeviceName = new javax.swing.JTextField();
        label4 = new javax.swing.JLabel();
        scrollpane1 = new javax.swing.JScrollPane();
        tableItems = new javax.swing.JTable();
        label5 = new javax.swing.JLabel();
        tfieldUpdatePeriod = new javax.swing.JTextField();
        buttonStart = new javax.swing.JButton();
        buttonStop = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setMaximumSize(new java.awt.Dimension(1160, 940));
        setMinimumSize(new java.awt.Dimension(1160, 940));
        setPreferredSize(new java.awt.Dimension(1160, 940));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTemplateInfo.setBackground(new java.awt.Color(73, 125, 222));
        panelTemplateInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        label1.setText("Template Name:");
        panelTemplateInfo.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, 40));

        tfieldTemplateName.setEditable(false);
        tfieldTemplateName.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tfieldTemplateName.setText(". . .");
        tfieldTemplateName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        tfieldTemplateName.setOpaque(false);
        tfieldTemplateName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfieldTemplateNameActionPerformed(evt);
            }
        });
        panelTemplateInfo.add(tfieldTemplateName, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 330, 40));

        label2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        label2.setText("Device Name:");
        panelTemplateInfo.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, 40));

        tfieldDeviceName.setEditable(false);
        tfieldDeviceName.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tfieldDeviceName.setText(". . .");
        tfieldDeviceName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        tfieldDeviceName.setOpaque(false);
        tfieldDeviceName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfieldDeviceNameActionPerformed(evt);
            }
        });
        panelTemplateInfo.add(tfieldDeviceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 330, 40));

        getContentPane().add(panelTemplateInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 220));

        label4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        label4.setText("Items:");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, 60));

        tableItems.setBorder(null);
        tableItems.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        tableItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollpane1.setViewportView(tableItems);

        getContentPane().add(scrollpane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 950, 540));

        label5.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        label5.setText("Update Period (s):");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 860, -1, 30));

        tfieldUpdatePeriod.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        tfieldUpdatePeriod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfieldUpdatePeriod.setText("0");
        getContentPane().add(tfieldUpdatePeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 860, 90, 30));

        buttonStart.setBackground(new java.awt.Color(73, 125, 222));
        buttonStart.setForeground(java.awt.Color.white);
        buttonStart.setText("Start");
        getContentPane().add(buttonStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 860, 70, -1));

        buttonStop.setBackground(new java.awt.Color(73, 125, 222));
        buttonStop.setForeground(java.awt.Color.white);
        buttonStop.setText("Stop");
        getContentPane().add(buttonStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 860, 70, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel1.setText("Updated Time:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 858, 140, 30));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel2.setText(". . .");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 858, 180, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfieldTemplateNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfieldTemplateNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfieldTemplateNameActionPerformed

    private void tfieldDeviceNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfieldDeviceNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfieldDeviceNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelMonitoringDevices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelMonitoringDevices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelMonitoringDevices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelMonitoringDevices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelMonitoringDevices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonStart;
    private javax.swing.JButton buttonStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JPanel panelTemplateInfo;
    private javax.swing.JScrollPane scrollpane1;
    private javax.swing.JTable tableItems;
    private javax.swing.JTextField tfieldDeviceName;
    private javax.swing.JTextField tfieldTemplateName;
    private javax.swing.JTextField tfieldUpdatePeriod;
    // End of variables declaration//GEN-END:variables
}
