/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guidesign;

/**
 *
 * @author cloud
 */
public class PanelSettings extends javax.swing.JFrame {

    /**
     * Creates new form PanelSettings
     */
    public PanelSettings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSystemSettings = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        cboxLanguage = new javax.swing.JComboBox<>();
        label2 = new javax.swing.JLabel();
        cboxTheme = new javax.swing.JComboBox<>();
        panelOperationSettings = new javax.swing.JPanel();
        label3 = new javax.swing.JLabel();
        tfieldDevicePeriod = new javax.swing.JTextField();
        label4 = new javax.swing.JLabel();
        tfieldInterfacePeriod = new javax.swing.JTextField();
        tfieldMonitoringPeriod = new javax.swing.JTextField();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        tfieldMaxTableIndex = new javax.swing.JTextField();
        buttonRestoreDefault = new javax.swing.JButton();
        buttonSaveApply = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 940));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSystemSettings.setBackground(java.awt.Color.white);
        panelSystemSettings.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "System Settings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14))); // NOI18N
        panelSystemSettings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setBackground(java.awt.Color.blue);
        label1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        label1.setForeground(java.awt.Color.blue);
        label1.setText("Language");
        panelSystemSettings.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, 30));

        cboxLanguage.setBackground(java.awt.Color.white);
        cboxLanguage.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        cboxLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboxLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxLanguageActionPerformed(evt);
            }
        });
        panelSystemSettings.add(cboxLanguage, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 210, 30));

        label2.setBackground(java.awt.Color.blue);
        label2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        label2.setForeground(java.awt.Color.blue);
        label2.setText("Theme");
        panelSystemSettings.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, 30));

        cboxTheme.setBackground(java.awt.Color.white);
        cboxTheme.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        cboxTheme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboxTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxThemeActionPerformed(evt);
            }
        });
        panelSystemSettings.add(cboxTheme, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 210, 30));

        getContentPane().add(panelSystemSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 510, 620));

        panelOperationSettings.setBackground(java.awt.Color.white);
        panelOperationSettings.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "OperationSettings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14))); // NOI18N
        panelOperationSettings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        label3.setForeground(java.awt.Color.blue);
        label3.setText("Device Checking Period (s)");
        panelOperationSettings.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, 30));

        tfieldDevicePeriod.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        tfieldDevicePeriod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfieldDevicePeriod.setText("0");
        tfieldDevicePeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfieldDevicePeriodActionPerformed(evt);
            }
        });
        panelOperationSettings.add(tfieldDevicePeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 100, 30));

        label4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        label4.setForeground(java.awt.Color.blue);
        label4.setText("Interface Checking Periods(s)");
        panelOperationSettings.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, 30));

        tfieldInterfacePeriod.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        tfieldInterfacePeriod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfieldInterfacePeriod.setText("0");
        panelOperationSettings.add(tfieldInterfacePeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 100, 30));

        tfieldMonitoringPeriod.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        tfieldMonitoringPeriod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfieldMonitoringPeriod.setText("0");
        panelOperationSettings.add(tfieldMonitoringPeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 100, 30));

        label5.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        label5.setForeground(java.awt.Color.blue);
        label5.setText("Monitoring Query  Periods(s)");
        panelOperationSettings.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, 30));

        label6.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        label6.setForeground(java.awt.Color.blue);
        label6.setText("Max Index Of Table");
        panelOperationSettings.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 30));

        tfieldMaxTableIndex.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        tfieldMaxTableIndex.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfieldMaxTableIndex.setText("10");
        panelOperationSettings.add(tfieldMaxTableIndex, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 100, 30));

        getContentPane().add(panelOperationSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, 510, 620));

        buttonRestoreDefault.setBackground(new java.awt.Color(66, 135, 245));
        buttonRestoreDefault.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonRestoreDefault.setForeground(java.awt.Color.white);
        buttonRestoreDefault.setText("Restore Default");
        buttonRestoreDefault.setBorderPainted(false);
        buttonRestoreDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRestoreDefaultActionPerformed(evt);
            }
        });
        getContentPane().add(buttonRestoreDefault, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 790, -1, 40));

        buttonSaveApply.setBackground(new java.awt.Color(66, 135, 245));
        buttonSaveApply.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonSaveApply.setForeground(java.awt.Color.white);
        buttonSaveApply.setText("Save And Apply");
        buttonSaveApply.setBorderPainted(false);
        getContentPane().add(buttonSaveApply, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 790, -1, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxLanguageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxLanguageActionPerformed

    private void cboxThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxThemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxThemeActionPerformed

    private void tfieldDevicePeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfieldDevicePeriodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfieldDevicePeriodActionPerformed

    private void buttonRestoreDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRestoreDefaultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRestoreDefaultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelSettings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRestoreDefault;
    private javax.swing.JButton buttonSaveApply;
    private javax.swing.JComboBox<String> cboxLanguage;
    private javax.swing.JComboBox<String> cboxTheme;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JPanel panelOperationSettings;
    private javax.swing.JPanel panelSystemSettings;
    private javax.swing.JTextField tfieldDevicePeriod;
    private javax.swing.JTextField tfieldInterfacePeriod;
    private javax.swing.JTextField tfieldMaxTableIndex;
    private javax.swing.JTextField tfieldMonitoringPeriod;
    // End of variables declaration//GEN-END:variables
}
