/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guidesign;

/**
 *
 * @author cloud
 */
public class PanelImportedDevices extends javax.swing.JFrame {

    /**
     * Creates new form PanelImportedDevices
     */
    public PanelImportedDevices() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelShowDeviceList = new javax.swing.JLabel();
        panelDevices = new javax.swing.JPanel();
        tfieldSearch = new javax.swing.JTextField();
        scrollpane1 = new javax.swing.JScrollPane();
        panelDeviceList = new javax.swing.JPanel();
        labelSearch = new javax.swing.JLabel();
        buttonImport = new javax.swing.JButton();
        buttonTopology = new javax.swing.JButton();
        labelHideDeviceList = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 940));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelShowDeviceList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_double_right_arrow_blue_40.png"))); // NOI18N
        getContentPane().add(labelShowDeviceList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 40, 190));

        panelDevices.setBackground(new java.awt.Color(20, 51, 125));
        panelDevices.setPreferredSize(new java.awt.Dimension(280, 940));
        panelDevices.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfieldSearch.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        tfieldSearch.setForeground(java.awt.Color.white);
        tfieldSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.white));
        tfieldSearch.setCaretColor(java.awt.Color.white);
        tfieldSearch.setOpaque(false);
        panelDevices.add(tfieldSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 310, 30));

        scrollpane1.setBackground(java.awt.Color.white);
        scrollpane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelDeviceList.setBackground(java.awt.Color.white);
        panelDeviceList.setPreferredSize(new java.awt.Dimension(370, 738));
        panelDeviceList.setLayout(new javax.swing.BoxLayout(panelDeviceList, javax.swing.BoxLayout.PAGE_AXIS));
        scrollpane1.setViewportView(panelDeviceList);

        panelDevices.add(scrollpane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 360, 690));

        labelSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_search_40.png"))); // NOI18N
        panelDevices.add(labelSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 50, 30));

        buttonImport.setBackground(new java.awt.Color(38, 56, 163));
        buttonImport.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonImport.setForeground(java.awt.Color.white);
        buttonImport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_plus_40.png"))); // NOI18N
        buttonImport.setText("Import");
        buttonImport.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonImport.setBorderPainted(false);
        panelDevices.add(buttonImport, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 830, 120, 40));

        buttonTopology.setBackground(new java.awt.Color(38, 56, 163));
        buttonTopology.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonTopology.setForeground(java.awt.Color.white);
        buttonTopology.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_plus_40.png"))); // NOI18N
        buttonTopology.setText("Topology");
        buttonTopology.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonTopology.setBorderPainted(false);
        panelDevices.add(buttonTopology, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 830, 150, 40));

        labelHideDeviceList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_double_left_white_40.png"))); // NOI18N
        panelDevices.add(labelHideDeviceList, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 30, 190));

        getContentPane().add(panelDevices, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelImportedDevices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelImportedDevices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelImportedDevices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelImportedDevices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelImportedDevices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonImport;
    private javax.swing.JButton buttonTopology;
    private javax.swing.JLabel labelHideDeviceList;
    private javax.swing.JLabel labelSearch;
    private javax.swing.JLabel labelShowDeviceList;
    private javax.swing.JPanel panelDeviceList;
    private javax.swing.JPanel panelDevices;
    private javax.swing.JScrollPane scrollpane1;
    private javax.swing.JTextField tfieldSearch;
    // End of variables declaration//GEN-END:variables
}
