/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guidesign;

/**
 *
 * @author danh.nguyentranbao
 */
public class PanelMonitor extends javax.swing.JPanel {

    /**
     * Creates new form PanelMonitor
     */
    public PanelMonitor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDevice = new javax.swing.JLabel();
        labelDeviceValue = new javax.swing.JLabel();
        labelIPAddress = new javax.swing.JLabel();
        labelIPAddressValue = new javax.swing.JLabel();
        labelSNMPVersion = new javax.swing.JLabel();
        labelPeriods = new javax.swing.JLabel();
        labelSNMPVersionValue = new javax.swing.JLabel();
        tfieldPeriod = new javax.swing.JTextField();
        scrollpaneItemValues = new javax.swing.JScrollPane();
        tableItemValues = new javax.swing.JTable();
        buttonStart = new javax.swing.JButton();
        buttonStop = new javax.swing.JButton();
        buttonNextTable = new javax.swing.JButton();
        buttonPreviousTable = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1500, 900));
        setLayout(null);

        labelDevice.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labelDevice.setText("Device:");
        add(labelDevice);
        labelDevice.setBounds(70, 60, 40, 16);

        labelDeviceValue.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labelDeviceValue.setText(". . .");
        add(labelDeviceValue);
        labelDeviceValue.setBounds(120, 60, 18, 14);

        labelIPAddress.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labelIPAddress.setText("IP Address:");
        add(labelIPAddress);
        labelIPAddress.setBounds(240, 60, 63, 16);

        labelIPAddressValue.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labelIPAddressValue.setText(". . .");
        add(labelIPAddressValue);
        labelIPAddressValue.setBounds(310, 60, 18, 14);

        labelSNMPVersion.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labelSNMPVersion.setText("SNMP Version:");
        add(labelSNMPVersion);
        labelSNMPVersion.setBounds(410, 60, 82, 16);

        labelPeriods.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labelPeriods.setText("Period (s):");
        add(labelPeriods);
        labelPeriods.setBounds(730, 60, 57, 16);

        labelSNMPVersionValue.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labelSNMPVersionValue.setText(". . .");
        add(labelSNMPVersionValue);
        labelSNMPVersionValue.setBounds(500, 60, 18, 14);

        tfieldPeriod.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        add(tfieldPeriod);
        tfieldPeriod.setBounds(790, 60, 64, 22);

        tableItemValues.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollpaneItemValues.setViewportView(tableItemValues);

        add(scrollpaneItemValues);
        scrollpaneItemValues.setBounds(72, 111, 1347, 716);

        buttonStart.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        buttonStart.setText("Start");
        buttonStart.setMaximumSize(new java.awt.Dimension(60, 30));
        buttonStart.setMinimumSize(new java.awt.Dimension(60, 30));
        buttonStart.setPreferredSize(new java.awt.Dimension(60, 30));
        add(buttonStart);
        buttonStart.setBounds(870, 55, 60, 30);

        buttonStop.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        buttonStop.setText("Stop");
        buttonStop.setMaximumSize(new java.awt.Dimension(60, 30));
        buttonStop.setMinimumSize(new java.awt.Dimension(60, 30));
        buttonStop.setPreferredSize(new java.awt.Dimension(60, 30));
        add(buttonStop);
        buttonStop.setBounds(940, 55, 60, 30);

        buttonNextTable.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        buttonNextTable.setText("Previous");
        buttonNextTable.setMaximumSize(new java.awt.Dimension(75, 25));
        buttonNextTable.setMinimumSize(new java.awt.Dimension(75, 25));
        buttonNextTable.setPreferredSize(new java.awt.Dimension(75, 25));
        add(buttonNextTable);
        buttonNextTable.setBounds(1250, 850, 73, 23);

        buttonPreviousTable.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        buttonPreviousTable.setText("Next");
        buttonPreviousTable.setMaximumSize(new java.awt.Dimension(75, 25));
        buttonPreviousTable.setMinimumSize(new java.awt.Dimension(75, 25));
        buttonPreviousTable.setPreferredSize(new java.awt.Dimension(75, 25));
        add(buttonPreviousTable);
        buttonPreviousTable.setBounds(1340, 850, 73, 23);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNextTable;
    private javax.swing.JButton buttonPreviousTable;
    private javax.swing.JButton buttonStart;
    private javax.swing.JButton buttonStop;
    private javax.swing.JLabel labelDevice;
    private javax.swing.JLabel labelDeviceValue;
    private javax.swing.JLabel labelIPAddress;
    private javax.swing.JLabel labelIPAddressValue;
    private javax.swing.JLabel labelPeriods;
    private javax.swing.JLabel labelSNMPVersion;
    private javax.swing.JLabel labelSNMPVersionValue;
    private javax.swing.JScrollPane scrollpaneItemValues;
    private javax.swing.JTable tableItemValues;
    private javax.swing.JTextField tfieldPeriod;
    // End of variables declaration//GEN-END:variables
}
