/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guidesign;

/**
 *
 * @author cloud
 */
public class PanelCreate extends javax.swing.JPanel {

    /**
     * Creates new form PanelCreate
     */
    public PanelCreate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1500, 900));
        setLayout(null);

        jTextField1.setMaximumSize(new java.awt.Dimension(300, 50));
        jTextField1.setMinimumSize(new java.awt.Dimension(300, 50));
        jTextField1.setPreferredSize(new java.awt.Dimension(300, 50));
        add(jTextField1);
        jTextField1.setBounds(660, 450, 300, 50);

        jTextField2.setMaximumSize(new java.awt.Dimension(300, 50));
        jTextField2.setMinimumSize(new java.awt.Dimension(300, 50));
        jTextField2.setPreferredSize(new java.awt.Dimension(300, 50));
        add(jTextField2);
        jTextField2.setBounds(660, 520, 300, 50);

        jLabel3.setText("Full Name");
        jLabel3.setMaximumSize(new java.awt.Dimension(120, 50));
        jLabel3.setMinimumSize(new java.awt.Dimension(120, 50));
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 50));
        add(jLabel3);
        jLabel3.setBounds(540, 130, 120, 50);

        jTextField3.setMaximumSize(new java.awt.Dimension(300, 50));
        jTextField3.setMinimumSize(new java.awt.Dimension(300, 50));
        jTextField3.setPreferredSize(new java.awt.Dimension(300, 50));
        jTextField3.setRequestFocusEnabled(false);
        add(jTextField3);
        jTextField3.setBounds(660, 120, 300, 50);

        jLabel4.setText("Age");
        jLabel4.setMaximumSize(new java.awt.Dimension(120, 50));
        jLabel4.setMinimumSize(new java.awt.Dimension(120, 50));
        jLabel4.setPreferredSize(new java.awt.Dimension(120, 50));
        add(jLabel4);
        jLabel4.setBounds(540, 200, 120, 50);

        jTextField4.setMaximumSize(new java.awt.Dimension(300, 50));
        jTextField4.setMinimumSize(new java.awt.Dimension(300, 50));
        jTextField4.setPreferredSize(new java.awt.Dimension(300, 50));
        add(jTextField4);
        jTextField4.setBounds(660, 190, 300, 50);

        jLabel5.setText("Position");
        jLabel5.setMaximumSize(new java.awt.Dimension(120, 50));
        jLabel5.setMinimumSize(new java.awt.Dimension(120, 50));
        jLabel5.setPreferredSize(new java.awt.Dimension(120, 50));
        add(jLabel5);
        jLabel5.setBounds(540, 260, 120, 50);

        jTextField5.setMaximumSize(new java.awt.Dimension(300, 50));
        jTextField5.setMinimumSize(new java.awt.Dimension(300, 50));
        jTextField5.setPreferredSize(new java.awt.Dimension(300, 50));
        add(jTextField5);
        jTextField5.setBounds(660, 260, 300, 50);

        jLabel6.setText("Contact Number");
        jLabel6.setMaximumSize(new java.awt.Dimension(120, 50));
        jLabel6.setMinimumSize(new java.awt.Dimension(120, 50));
        jLabel6.setPreferredSize(new java.awt.Dimension(120, 50));
        add(jLabel6);
        jLabel6.setBounds(540, 330, 120, 50);

        jTextField6.setMaximumSize(new java.awt.Dimension(300, 50));
        jTextField6.setMinimumSize(new java.awt.Dimension(300, 50));
        jTextField6.setPreferredSize(new java.awt.Dimension(300, 50));
        add(jTextField6);
        jTextField6.setBounds(660, 330, 300, 50);

        jLabel1.setText("Account");
        jLabel1.setMaximumSize(new java.awt.Dimension(120, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(120, 50));
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 50));
        add(jLabel1);
        jLabel1.setBounds(540, 450, 120, 50);

        jLabel7.setText("Password");
        jLabel7.setMaximumSize(new java.awt.Dimension(120, 50));
        jLabel7.setMinimumSize(new java.awt.Dimension(120, 50));
        jLabel7.setPreferredSize(new java.awt.Dimension(120, 50));
        add(jLabel7);
        jLabel7.setBounds(540, 520, 120, 50);

        jLabel8.setText("Confirm");
        jLabel8.setMaximumSize(new java.awt.Dimension(120, 50));
        jLabel8.setMinimumSize(new java.awt.Dimension(120, 50));
        jLabel8.setPreferredSize(new java.awt.Dimension(120, 50));
        add(jLabel8);
        jLabel8.setBounds(540, 590, 120, 50);

        jTextField7.setMaximumSize(new java.awt.Dimension(300, 50));
        jTextField7.setMinimumSize(new java.awt.Dimension(300, 50));
        jTextField7.setPreferredSize(new java.awt.Dimension(300, 50));
        add(jTextField7);
        jTextField7.setBounds(660, 590, 300, 50);

        jCheckBox1.setText("I have read and agree to the term of service");
        add(jCheckBox1);
        jCheckBox1.setBounds(570, 670, 350, 24);

        jButton1.setText("Create");
        jButton1.setMaximumSize(new java.awt.Dimension(100, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 50));
        add(jButton1);
        jButton1.setBounds(750, 710, 100, 50);

        jButton2.setText("Cancel");
        jButton2.setMaximumSize(new java.awt.Dimension(100, 50));
        jButton2.setMinimumSize(new java.awt.Dimension(100, 50));
        jButton2.setPreferredSize(new java.awt.Dimension(100, 50));
        add(jButton2);
        jButton2.setBounds(860, 710, 100, 50);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
