/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guidesign;

/**
 *
 * @author cloud
 */
public class PanelDeviceInfo extends javax.swing.JPanel {

    /**
     * Creates new form PanelDeviceInfo
     */
    public PanelDeviceInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelName = new javax.swing.JLabel();
        labelType = new javax.swing.JLabel();
        labelDescription = new javax.swing.JLabel();
        labelLabel = new javax.swing.JLabel();
        labelSNMPVersion = new javax.swing.JLabel();
        labelIPAddress = new javax.swing.JLabel();
        labelCommunity = new javax.swing.JLabel();
        labelState = new javax.swing.JLabel();
        labelImportedTime = new javax.swing.JLabel();
        labelLastAccess = new javax.swing.JLabel();
        tfieldName = new javax.swing.JTextField();
        cboxType = new javax.swing.JComboBox<>();
        tfieldLabel = new javax.swing.JTextField();
        tfieldSNMPVersion = new javax.swing.JTextField();
        tfieldIPAddress = new javax.swing.JTextField();
        tfieldCommunity = new javax.swing.JTextField();
        labelStateValue = new javax.swing.JLabel();
        labelImportedTimeValue = new javax.swing.JLabel();
        labelLastAccessValue = new javax.swing.JLabel();
        buttonSaveInfo = new javax.swing.JButton();
        buttonCancelInfo = new javax.swing.JButton();
        scrollpaneDescription = new javax.swing.JScrollPane();
        tareaDescription = new javax.swing.JTextArea();
        scrollpaneTemplates = new javax.swing.JScrollPane();
        listTemplates = new javax.swing.JList<>();
        labelTemplates = new javax.swing.JLabel();
        buttonAddTemplates = new javax.swing.JButton();
        buttonCancelTemplates = new javax.swing.JButton();
        buttonMonitor = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1500, 900));
        setMinimumSize(new java.awt.Dimension(1500, 900));
        setLayout(null);

        labelName.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelName.setText("Name:");
        labelName.setMaximumSize(new java.awt.Dimension(120, 20));
        labelName.setMinimumSize(new java.awt.Dimension(120, 20));
        labelName.setPreferredSize(new java.awt.Dimension(120, 20));
        add(labelName);
        labelName.setBounds(220, 180, 120, 20);

        labelType.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelType.setText("Type:");
        labelType.setMaximumSize(new java.awt.Dimension(120, 20));
        labelType.setMinimumSize(new java.awt.Dimension(120, 20));
        labelType.setPreferredSize(new java.awt.Dimension(120, 20));
        add(labelType);
        labelType.setBounds(220, 230, 120, 20);

        labelDescription.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelDescription.setText("Description:");
        labelDescription.setMaximumSize(new java.awt.Dimension(120, 20));
        labelDescription.setMinimumSize(new java.awt.Dimension(120, 20));
        labelDescription.setPreferredSize(new java.awt.Dimension(120, 20));
        add(labelDescription);
        labelDescription.setBounds(220, 280, 120, 20);

        labelLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelLabel.setText("Label:");
        labelLabel.setMaximumSize(new java.awt.Dimension(120, 20));
        labelLabel.setMinimumSize(new java.awt.Dimension(120, 20));
        labelLabel.setPreferredSize(new java.awt.Dimension(120, 20));
        add(labelLabel);
        labelLabel.setBounds(220, 420, 120, 20);

        labelSNMPVersion.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelSNMPVersion.setText("SNMP Version:");
        labelSNMPVersion.setMaximumSize(new java.awt.Dimension(120, 20));
        labelSNMPVersion.setMinimumSize(new java.awt.Dimension(120, 20));
        labelSNMPVersion.setPreferredSize(new java.awt.Dimension(120, 20));
        add(labelSNMPVersion);
        labelSNMPVersion.setBounds(220, 470, 120, 20);

        labelIPAddress.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelIPAddress.setText("IP Address:");
        labelIPAddress.setMaximumSize(new java.awt.Dimension(120, 20));
        labelIPAddress.setMinimumSize(new java.awt.Dimension(120, 20));
        labelIPAddress.setPreferredSize(new java.awt.Dimension(120, 20));
        add(labelIPAddress);
        labelIPAddress.setBounds(220, 520, 120, 20);

        labelCommunity.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelCommunity.setText("Community:");
        labelCommunity.setMaximumSize(new java.awt.Dimension(120, 20));
        labelCommunity.setMinimumSize(new java.awt.Dimension(120, 20));
        labelCommunity.setPreferredSize(new java.awt.Dimension(120, 20));
        add(labelCommunity);
        labelCommunity.setBounds(220, 570, 120, 20);

        labelState.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelState.setText("State:");
        labelState.setMaximumSize(new java.awt.Dimension(120, 20));
        labelState.setMinimumSize(new java.awt.Dimension(120, 20));
        labelState.setPreferredSize(new java.awt.Dimension(120, 20));
        add(labelState);
        labelState.setBounds(220, 620, 120, 20);

        labelImportedTime.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelImportedTime.setText("Imported Time:");
        labelImportedTime.setMaximumSize(new java.awt.Dimension(120, 20));
        labelImportedTime.setMinimumSize(new java.awt.Dimension(120, 20));
        labelImportedTime.setPreferredSize(new java.awt.Dimension(120, 20));
        add(labelImportedTime);
        labelImportedTime.setBounds(220, 670, 120, 20);

        labelLastAccess.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelLastAccess.setText("Last Access:");
        labelLastAccess.setMaximumSize(new java.awt.Dimension(120, 20));
        labelLastAccess.setMinimumSize(new java.awt.Dimension(120, 20));
        labelLastAccess.setPreferredSize(new java.awt.Dimension(120, 20));
        add(labelLastAccess);
        labelLastAccess.setBounds(220, 710, 120, 20);

        tfieldName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tfieldName.setMaximumSize(new java.awt.Dimension(300, 30));
        tfieldName.setMinimumSize(new java.awt.Dimension(300, 30));
        tfieldName.setPreferredSize(new java.awt.Dimension(300, 30));
        tfieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfieldNameActionPerformed(evt);
            }
        });
        add(tfieldName);
        tfieldName.setBounds(360, 180, 300, 30);

        cboxType.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cboxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cboxType);
        cboxType.setBounds(360, 230, 150, 27);

        tfieldLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tfieldLabel.setMaximumSize(new java.awt.Dimension(300, 30));
        tfieldLabel.setMinimumSize(new java.awt.Dimension(300, 30));
        tfieldLabel.setPreferredSize(new java.awt.Dimension(300, 30));
        add(tfieldLabel);
        tfieldLabel.setBounds(360, 420, 300, 30);

        tfieldSNMPVersion.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tfieldSNMPVersion.setMaximumSize(new java.awt.Dimension(300, 30));
        tfieldSNMPVersion.setMinimumSize(new java.awt.Dimension(300, 30));
        tfieldSNMPVersion.setPreferredSize(new java.awt.Dimension(300, 30));
        add(tfieldSNMPVersion);
        tfieldSNMPVersion.setBounds(360, 470, 300, 30);

        tfieldIPAddress.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tfieldIPAddress.setMaximumSize(new java.awt.Dimension(300, 30));
        tfieldIPAddress.setMinimumSize(new java.awt.Dimension(300, 30));
        tfieldIPAddress.setPreferredSize(new java.awt.Dimension(300, 30));
        add(tfieldIPAddress);
        tfieldIPAddress.setBounds(360, 520, 300, 30);

        tfieldCommunity.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tfieldCommunity.setMaximumSize(new java.awt.Dimension(300, 30));
        tfieldCommunity.setMinimumSize(new java.awt.Dimension(300, 30));
        tfieldCommunity.setPreferredSize(new java.awt.Dimension(300, 30));
        add(tfieldCommunity);
        tfieldCommunity.setBounds(360, 570, 300, 30);

        labelStateValue.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelStateValue.setText(". . .");
        labelStateValue.setMaximumSize(new java.awt.Dimension(300, 30));
        labelStateValue.setMinimumSize(new java.awt.Dimension(300, 30));
        labelStateValue.setPreferredSize(new java.awt.Dimension(300, 30));
        add(labelStateValue);
        labelStateValue.setBounds(360, 620, 300, 30);

        labelImportedTimeValue.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelImportedTimeValue.setText(". . .");
        labelImportedTimeValue.setMaximumSize(new java.awt.Dimension(300, 30));
        labelImportedTimeValue.setMinimumSize(new java.awt.Dimension(300, 30));
        labelImportedTimeValue.setPreferredSize(new java.awt.Dimension(300, 30));
        add(labelImportedTimeValue);
        labelImportedTimeValue.setBounds(360, 670, 20, 17);

        labelLastAccessValue.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelLastAccessValue.setText(". . .");
        labelLastAccessValue.setMaximumSize(new java.awt.Dimension(300, 30));
        labelLastAccessValue.setMinimumSize(new java.awt.Dimension(300, 30));
        labelLastAccessValue.setPreferredSize(new java.awt.Dimension(300, 30));
        add(labelLastAccessValue);
        labelLastAccessValue.setBounds(360, 710, 20, 17);

        buttonSaveInfo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        buttonSaveInfo.setText("Save");
        buttonSaveInfo.setMaximumSize(new java.awt.Dimension(100, 40));
        buttonSaveInfo.setMinimumSize(new java.awt.Dimension(100, 40));
        buttonSaveInfo.setPreferredSize(new java.awt.Dimension(100, 40));
        add(buttonSaveInfo);
        buttonSaveInfo.setBounds(440, 760, 100, 40);

        buttonCancelInfo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        buttonCancelInfo.setText("Cancel");
        buttonCancelInfo.setMaximumSize(new java.awt.Dimension(100, 40));
        buttonCancelInfo.setMinimumSize(new java.awt.Dimension(100, 40));
        buttonCancelInfo.setPreferredSize(new java.awt.Dimension(100, 40));
        add(buttonCancelInfo);
        buttonCancelInfo.setBounds(550, 760, 100, 40);

        tareaDescription.setColumns(20);
        tareaDescription.setRows(5);
        scrollpaneDescription.setViewportView(tareaDescription);

        add(scrollpaneDescription);
        scrollpaneDescription.setBounds(360, 280, 300, 120);

        listTemplates.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        listTemplates.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollpaneTemplates.setViewportView(listTemplates);

        add(scrollpaneTemplates);
        scrollpaneTemplates.setBounds(880, 220, 410, 430);

        labelTemplates.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelTemplates.setText("Templates:");
        add(labelTemplates);
        labelTemplates.setBounds(880, 180, 100, 30);

        buttonAddTemplates.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        buttonAddTemplates.setText("Add");
        buttonAddTemplates.setMaximumSize(new java.awt.Dimension(100, 40));
        buttonAddTemplates.setMinimumSize(new java.awt.Dimension(100, 40));
        buttonAddTemplates.setPreferredSize(new java.awt.Dimension(100, 40));
        add(buttonAddTemplates);
        buttonAddTemplates.setBounds(1070, 680, 100, 40);

        buttonCancelTemplates.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        buttonCancelTemplates.setText("Cancel");
        buttonCancelTemplates.setMaximumSize(new java.awt.Dimension(100, 40));
        buttonCancelTemplates.setMinimumSize(new java.awt.Dimension(100, 40));
        buttonCancelTemplates.setPreferredSize(new java.awt.Dimension(100, 40));
        add(buttonCancelTemplates);
        buttonCancelTemplates.setBounds(1190, 680, 100, 40);

        buttonMonitor.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        buttonMonitor.setText("Monitor");
        buttonMonitor.setMaximumSize(new java.awt.Dimension(100, 40));
        buttonMonitor.setMinimumSize(new java.awt.Dimension(100, 40));
        buttonMonitor.setPreferredSize(new java.awt.Dimension(100, 40));
        add(buttonMonitor);
        buttonMonitor.setBounds(880, 680, 100, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void tfieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfieldNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddTemplates;
    private javax.swing.JButton buttonCancelInfo;
    private javax.swing.JButton buttonCancelTemplates;
    private javax.swing.JButton buttonMonitor;
    private javax.swing.JButton buttonSaveInfo;
    private javax.swing.JComboBox<String> cboxType;
    private javax.swing.JLabel labelCommunity;
    private javax.swing.JLabel labelDescription;
    private javax.swing.JLabel labelIPAddress;
    private javax.swing.JLabel labelImportedTime;
    private javax.swing.JLabel labelImportedTimeValue;
    private javax.swing.JLabel labelLabel;
    private javax.swing.JLabel labelLastAccess;
    private javax.swing.JLabel labelLastAccessValue;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelSNMPVersion;
    private javax.swing.JLabel labelState;
    private javax.swing.JLabel labelStateValue;
    private javax.swing.JLabel labelTemplates;
    private javax.swing.JLabel labelType;
    private javax.swing.JList<String> listTemplates;
    private javax.swing.JScrollPane scrollpaneDescription;
    private javax.swing.JScrollPane scrollpaneTemplates;
    private javax.swing.JTextArea tareaDescription;
    private javax.swing.JTextField tfieldCommunity;
    private javax.swing.JTextField tfieldIPAddress;
    private javax.swing.JTextField tfieldLabel;
    private javax.swing.JTextField tfieldName;
    private javax.swing.JTextField tfieldSNMPVersion;
    // End of variables declaration//GEN-END:variables
}
