/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guidesign;

import java.awt.Color;

/**
 *
 * @author cloud
 */
public class PanelNotificationList extends javax.swing.JFrame {

    /**
     * Creates new form PanelNotificationList
     */
    public PanelNotificationList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollpane1 = new javax.swing.JScrollPane();
        tableNotifications = new javax.swing.JTable();
        cboxColdStart = new javax.swing.JCheckBox();
        cboxWarmStart = new javax.swing.JCheckBox();
        cboxLinkUp = new javax.swing.JCheckBox();
        cboxLinkDown = new javax.swing.JCheckBox();
        cboxAuthenticationFailure = new javax.swing.JCheckBox();
        cboxEGPLoss = new javax.swing.JCheckBox();
        cboxEnterprise = new javax.swing.JCheckBox();
        label1 = new javax.swing.JLabel();
        tfieldSearchDevice = new javax.swing.JTextField();
        labelIconSearch = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1600, 940));
        setMinimumSize(new java.awt.Dimension(1600, 940));
        setPreferredSize(new java.awt.Dimension(1600, 940));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollpane1.setBackground(java.awt.Color.white);
        scrollpane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tableNotifications.setBorder(null);
        tableNotifications.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        tableNotifications.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollpane1.setViewportView(tableNotifications);

        getContentPane().add(scrollpane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 142, 1395, 701));

        cboxColdStart.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        cboxColdStart.setText("Cold Start");
        getContentPane().add(cboxColdStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        cboxWarmStart.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        cboxWarmStart.setText("Warm Start");
        getContentPane().add(cboxWarmStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        cboxLinkUp.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        cboxLinkUp.setText("Link Up");
        getContentPane().add(cboxLinkUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        cboxLinkDown.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        cboxLinkDown.setText("Link Down");
        getContentPane().add(cboxLinkDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        cboxAuthenticationFailure.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        cboxAuthenticationFailure.setText("Authentication Failure");
        getContentPane().add(cboxAuthenticationFailure, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, -1));

        cboxEGPLoss.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        cboxEGPLoss.setText("EGP Loss");
        getContentPane().add(cboxEGPLoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, -1, -1));

        cboxEnterprise.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        cboxEnterprise.setText("Enterprise");
        getContentPane().add(cboxEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, -1, -1));

        label1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        label1.setForeground(java.awt.Color.blue);
        label1.setText("Device:");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 50, 80, 30));

        tfieldSearchDevice.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        getContentPane().add(tfieldSearchDevice, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 50, 370, 30));

        labelIconSearch.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        labelIconSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_search2_30.png"))); // NOI18N
        getContentPane().add(labelIconSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 50, 30, 30));

        label2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        label2.setForeground(java.awt.Color.blue);
        label2.setText("Notification Types:");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, 30));

        panel1.setBackground(new Color(145, 199, 235));
        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelNotificationList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelNotificationList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelNotificationList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelNotificationList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelNotificationList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cboxAuthenticationFailure;
    private javax.swing.JCheckBox cboxColdStart;
    private javax.swing.JCheckBox cboxEGPLoss;
    private javax.swing.JCheckBox cboxEnterprise;
    private javax.swing.JCheckBox cboxLinkDown;
    private javax.swing.JCheckBox cboxLinkUp;
    private javax.swing.JCheckBox cboxWarmStart;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel labelIconSearch;
    private javax.swing.JPanel panel1;
    private javax.swing.JScrollPane scrollpane1;
    private javax.swing.JTable tableNotifications;
    private javax.swing.JTextField tfieldSearchDevice;
    // End of variables declaration//GEN-END:variables
}
