/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guidesign;

/**
 *
 * @author cloud
 */
public class PanelDevices extends javax.swing.JPanel {

    /**
     * Creates new form PanelDevices
     */
    public PanelDevices() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTotal = new javax.swing.JLabel();
        labelTotalValue = new javax.swing.JLabel();
        labelEnabled = new javax.swing.JLabel();
        labelEnabledValue = new javax.swing.JLabel();
        labelDisabled = new javax.swing.JLabel();
        labelDisabledValue = new javax.swing.JLabel();
        buttonImport = new javax.swing.JButton();
        scrollpanelDevices = new javax.swing.JScrollPane();
        tableDevices = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(1500, 900));
        setMinimumSize(new java.awt.Dimension(1500, 900));
        setPreferredSize(new java.awt.Dimension(1500, 900));
        setLayout(null);

        labelTotal.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelTotal.setText("Total:");
        add(labelTotal);
        labelTotal.setBounds(170, 30, 36, 19);

        labelTotalValue.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelTotalValue.setText("...");
        labelTotalValue.setMaximumSize(new java.awt.Dimension(30, 19));
        labelTotalValue.setMinimumSize(new java.awt.Dimension(30, 19));
        labelTotalValue.setPreferredSize(new java.awt.Dimension(30, 19));
        add(labelTotalValue);
        labelTotalValue.setBounds(210, 30, 30, 19);

        labelEnabled.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelEnabled.setText("Enabled:");
        add(labelEnabled);
        labelEnabled.setBounds(270, 30, 56, 19);

        labelEnabledValue.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelEnabledValue.setText("...");
        labelEnabledValue.setMaximumSize(new java.awt.Dimension(30, 19));
        labelEnabledValue.setMinimumSize(new java.awt.Dimension(30, 19));
        labelEnabledValue.setPreferredSize(new java.awt.Dimension(30, 19));
        add(labelEnabledValue);
        labelEnabledValue.setBounds(330, 30, 30, 19);

        labelDisabled.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelDisabled.setText("Disabled:");
        add(labelDisabled);
        labelDisabled.setBounds(390, 30, 59, 19);

        labelDisabledValue.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelDisabledValue.setText("...");
        labelDisabledValue.setMaximumSize(new java.awt.Dimension(30, 19));
        labelDisabledValue.setMinimumSize(new java.awt.Dimension(30, 19));
        labelDisabledValue.setPreferredSize(new java.awt.Dimension(30, 19));
        add(labelDisabledValue);
        labelDisabledValue.setBounds(450, 30, 30, 19);

        buttonImport.setText("Import");
        buttonImport.setMaximumSize(new java.awt.Dimension(80, 30));
        buttonImport.setMinimumSize(new java.awt.Dimension(80, 30));
        buttonImport.setPreferredSize(new java.awt.Dimension(80, 30));
        add(buttonImport);
        buttonImport.setBounds(1210, 20, 80, 30);

        tableDevices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollpanelDevices.setViewportView(tableDevices);

        add(scrollpanelDevices);
        scrollpanelDevices.setBounds(60, 70, 1380, 770);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonImport;
    private javax.swing.JLabel labelDisabled;
    private javax.swing.JLabel labelDisabledValue;
    private javax.swing.JLabel labelEnabled;
    private javax.swing.JLabel labelEnabledValue;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelTotalValue;
    private javax.swing.JScrollPane scrollpanelDevices;
    private javax.swing.JTable tableDevices;
    // End of variables declaration//GEN-END:variables
}
